### ISSUE TITLE
Please help me figure out why SMS is not installed

### ISSUE THREAD

**Issue by aukc1970** [XHiddenProjects1/WebPress#11]
Good afternoon I wanted to install the CMS locally on the local Laragon server, but nothing is learned, an error appears Warning: Invalid argument supplied for foreach() in C:\laragon\www\webpress\WebPress\libs\users.lib.php on line 339

Fatal error: Uncaught TypeError: Return value of Users::ListUsers() must be of the type array, null returned in C:\laragon\www\webpress\WebPress\libs\users.lib.php:342 Stack trace: #0 C:\laragon\www\webpress\WebPress\plugins\Core\Core.plg.php(23): Users::ListUsers(false) #1 C:\laragon\www\webpress\WebPress\libs\plugin.lib. php(19): Core_head(NULL) #2 C:\laragon\www\webpress\WebPress\libs\plugin.lib.php(29): Plugin::myHook('head', 'Core', NULL) #3 C:\laragon\www\webpress\WebPress\header.php(207): Plugin::hook('head') #4 C:\laragon\www\webpress\WebPress\auth.php(14): head(' Register', '..') #5 {main} thrown in C:\laragon\www\webpress\WebPress\libs\users.lib.php on line 342

Please help me figure out why SMS is not installed

**Comment by XHiddenProjects** [comment]
I have fixed it, The User list wasn't returning an array, so I have fixed it to the return an empty array if no array is found! Hope that helps.
